### Registrar usuário
POST https://mmbadonis.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "MiguelMorenoBarbosa",
    "email": "miguelmorenobarbosa7@gmail.com",
    "password": "123456"
}

### Autenticar usuário
POST https://mmbadonis.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "miguelmorenobarbosa7@gmail.com",
    "password": "123456"
}